Repository securesign/rekor, pull requests merged in 2023-11, with the labels that each got.

#145 rhtap: update Dockerfile to get a clean git hash
  redhat/overlays/Dockerfile.cli
Labels: approved

#148 :robot: triggering CI on branch 'redhat-v1.2.2' after synching from upstream/v1.2.2
  Dockerfile.cli
  ci
  redhat/overlays/Dockerfile.cli
Labels: kind/sync-fork-to-upstream, approved

#150 pipelines: add source image build
  .tekton/backfill-redis-pull-request.yaml
  .tekton/backfill-redis-push.yaml
  .tekton/rekor-cli-pull-request.yaml
  .tekton/rekor-cli-push.yaml
  .tekton/rekor-server-pull-request.yaml
  .tekton/rekor-server-push.yaml
Labels: approved, lgtm

#156 :robot: triggering CI on branch 'redhat-v1.2.2' after synching from upstream/v1.2.2
  Dockerfile
  Dockerfile.backfill-redis
  Dockerfile.cli
  ci
  redhat/overlays/Dockerfile
  redhat/overlays/Dockerfile.backfill-redis
  redhat/overlays/Dockerfile.cli
Labels: kind/sync-fork-to-upstream, approved

#159 removing args on rhel9/redis-6 image
  .tekton/rekor-e2e-test.yaml
  docker-compose.yml
Labels: lgtm

#162 chore: copy overlays from midstream-v1.2.2
  Build.mak
  Dockerfile
  Dockerfile.backfill-redis
  Dockerfile.cli
  cmd/rekor-server/e2e_test.go
  e2e-test.sh
Labels: lgtm

#173 [SECURESIGN-247] Adding necessary files for build and RHTAP Onboarding
  .dockerignore
Labels: lgtm

#174 Updating Dockerfile with extra go mod vendor.
  Dockerfile.cli
Labels: lgtm

#168 enabling source builds in rekor-1-0-gamma components
  .tekton/backfill-redis-1-0-gamma-pull-request.yaml
  .tekton/backfill-redis-1-0-gamma-push.yaml
  .tekton/rekor-server-1-0-gamma-pull-request.yaml
  .tekton/rekor-server-1-0-gamma-push.yaml
Labels: lgtm

#177 [SECURESIGN-252] | Enabling build-source-image for cli.
  .tekton/rekor-cli-1-3-pull-request.yaml
  .tekton/rekor-cli-1-3-push.yaml
Labels: lgtm

#169 enable hermetic builds and prefetched dependencies
  .dockerignore
  .tekton/backfill-redis-1-0-gamma-pull-request.yaml
  .tekton/backfill-redis-1-0-gamma-push.yaml
  .tekton/rekor-server-1-0-gamma-pull-request.yaml
  .tekton/rekor-server-1-0-gamma-push.yaml
  Dockerfile
  Dockerfile.backfill-redis
  Dockerfile.cli
Labels: do-not-merge/hold
